import type { Question } from "./types";

export const infrastructureQuestions: Question[] = [
  {
    id: "INF-001",
    criterion: "Área de toma radiográfica",
    text: "¿Cuenta con un área exclusiva y delimitada para la toma de radiografías dentales?",
    reference: "Res. 3100/2019 - Estándar de infraestructura",
    findingText: "No se cuenta con un área exclusiva para la toma radiográfica.",
    recommendation: "Delimitar o construir un espacio físico exclusivo para el equipo de rayos X.",
  },
  {
    id: "INF-002",
    criterion: "Dimensiones del área",
    text: "¿El área de rayos X cumple con las dimensiones mínimas establecidas para el equipo instalado?",
    reference: "Anexo Técnico - Radiología Odontológica",
    findingText: "Las dimensiones del área no cumplen los mínimos requeridos.",
    recommendation: "Ajustar las dimensiones del área según el manual del fabricante y el cálculo de blindaje.",
  },
  {
    id: "INF-003",
    criterion: "Blindaje radiológico - paredes",
    text: "¿Las paredes del área de rayos X cuentan con blindaje plomado o equivalente certificado por un experto en protección radiológica?",
    reference: "Res. 3100/2019 + Res. 181434/2002",
    findingText: "Las paredes no cuentan con blindaje certificado.",
    recommendation: "Contratar experto para calcular e instalar el blindaje necesario (plomo, barita, etc.).",
    isCritical: true,
  },
  {
    id: "INF-004",
    criterion: "Blindaje radiológico - puerta",
    text: "¿La puerta del área de rayos X cuenta con blindaje plomado o equivalente?",
    reference: "Res. 3100/2019 + Protección radiológica",
    findingText: "La puerta no tiene blindaje adecuado.",
    recommendation: "Instalar lámina de plomo en la puerta o cambiar por una puerta plomada certificada.",
  },
  {
    id: "INF-005",
    criterion: "Blindaje radiológico - visor",
    text: "¿Existe un visor plomado que permita observar al paciente durante la toma radiográfica?",
    reference: "Estándar de protección radiológica",
    findingText: "Ausencia de visor plomado para observación del paciente.",
    recommendation: "Instalar vidrio plomado en pared o puerta con el equivalente en plomo calculado.",
  },
  {
    id: "INF-006",
    criterion: "Señalización radiológica",
    text: "¿El área cuenta con señalización de advertencia de radiación ionizante (símbolo trébol) visible en el acceso?",
    reference: "Res. 3100/2019 - Señalización",
    findingText: "Falta señalización internacional de advertencia de radiación.",
    recommendation: "Instalar el símbolo de trébol magenta/negro sobre fondo amarillo en la puerta de acceso.",
    isCritical: true,
  },
  {
    id: "INF-007",
    criterion: "Señalización luminosa",
    text: "¿Existe señalización luminosa (luz roja) que indique cuando el equipo está en operación?",
    reference: "Protección radiológica",
    findingText: "No hay advertencia luminosa durante la emisión de rayos X.",
    recommendation: "Instalar luz roja conectada al disparo del equipo en la parte externa del ambiente.",
  },
  {
    id: "INF-008",
    criterion: "Acabados - pisos",
    text: "¿Los pisos son de material lavable, liso, de fácil limpieza y desinfección?",
    reference: "Res. 3100/2019 - Infraestructura",
    findingText: "Los pisos no cumplen con las características de higiene (lavable, liso, sin porosidades).",
    recommendation: "Adecuar los pisos instalando material tipo vinilo, porcelanato u otro de fácil limpieza (uso de medias cañas recomendado).",
  },
  {
    id: "INF-009",
    criterion: "Acabados - paredes",
    text: "¿Las paredes son de material lavable, liso e impermeable hasta el techo?",
    reference: "Res. 3100/2019 - Infraestructura",
    findingText: "Las paredes presentan superficies porosas o materiales no lavables.",
    recommendation: "Pintar con pintura epóxica o instalar revestimiento lavable liso.",
  },
  {
    id: "INF-010",
    criterion: "Acabados - techos",
    text: "¿Los techos son de material resistente, lavable y con acabado de cielo raso?",
    reference: "Res. 3100/2019 - Infraestructura",
    findingText: "Acabado de techos inadecuado (poroso, difícil limpieza).",
    recommendation: "Instalar cielo raso liso y lavable.",
  },
  {
    id: "INF-011",
    criterion: "Ventilación",
    text: "¿El área cuenta con ventilación natural o mecánica adecuada?",
    reference: "Res. 3100/2019 - Condiciones ambientales",
    findingText: "Sistema de ventilación deficiente.",
    recommendation: "Instalar ventilación mecánica que garantice las renovaciones de aire por hora requeridas.",
  },
  {
    id: "INF-012",
    criterion: "Iluminación",
    text: "¿El área cuenta con iluminación natural y/o artificial suficiente para las actividades que se realizan?",
    reference: "Res. 3100/2019 - Condiciones ambientales",
    findingText: "Iluminación insuficiente en el área radiográfica.",
    recommendation: "Mejorar la capacidad de luxes instalando nuevas luminarias certificadas.",
  },
  {
    id: "INF-013",
    criterion: "Suministro de agua",
    text: "¿El servicio cuenta con suministro de agua potable permanente?",
    reference: "Res. 3100/2019 - Infraestructura",
    findingText: "Intermitencia o ausencia de suministro de agua potable.",
    recommendation: "Garantizar tanque de reserva que asegure agua potable o revisión de plomería.",
  },
  {
    id: "INF-014",
    criterion: "Suministro eléctrico",
    text: "¿El área tiene instalaciones eléctricas adecuadas y protegidas (tomas reguladas, puesta a tierra)?",
    reference: "Res. 3100/2019 - Instalaciones",
    findingText: "Instalación eléctrica insegura o sin puesta a tierra verificable.",
    recommendation: "Adecuar cableado según Reglamento RETIE e instalar UPS o tomas reguladas si es equipo digital.",
  },
  {
    id: "INF-015",
    criterion: "Área de procesamiento/lectura",
    text: "¿Cuenta con un espacio adecuado para la lectura/interpretación o procesamiento de imágenes?",
    reference: "Anexo Técnico - Radiología",
    findingText: "No se cuenta con un puesto de digitación o lectura de la imagen radiográfica.",
    recommendation: "Asignar área anexa con pantalla o negatoscopio para lectura e interpretación.",
  },
  {
    id: "INF-016",
    criterion: "Accesibilidad",
    text: "¿El acceso al área permite la movilidad de personas con discapacidad?",
    reference: "Res. 3100/2019 - Accesibilidad",
    findingText: "Barreras arquitectónicas (escalones sin rampa, puertas estrechas) impiden el acceso a PxD.",
    recommendation: "Ajustar ancho de marcos y eliminar desniveles; instalar rampas según estándares.",
  }
];

export const equipmentQuestions: Question[] = [
  {
    id: "DOT-001",
    criterion: "Equipo de rayos X",
    text: "¿Cuenta con equipo de rayos X dental (periapical/panorámico) en funcionamiento?",
    reference: "Res. 3100/2019 - Dotación",
    findingText: "No cuenta con equipo de radiología en funcionamiento.",
    recommendation: "Adquirir y realizar instalación funcional del equipo emisor de rayos X.",
    isCritical: true,
  },
  {
    id: "DOT-002",
    criterion: "Registro INVIMA",
    text: "¿El equipo de rayos X cuenta con registro sanitario INVIMA vigente?",
    reference: "Res. 3100/2019 - Dotación",
    findingText: "Equipo carece de Registro o Permiso INVIMA vigente.",
    recommendation: "Gestionar permiso de importación o registro ante entidad reguladora para el equipo.",
  },
  {
    id: "DOT-003",
    criterion: "Licencia de práctica médica",
    text: "¿Se cuenta con licencia de práctica expedida por la Secretaría de Salud departamental/distrital?",
    reference: "Res. 181434/2002",
    findingText: "Sin Licencia de práctica y manejo de fuentes de radiación ionizante.",
    recommendation: "Tramitar solicitud de Licencia aportando memorias de cálculo, manual de bioseguridad y QA.",
    isCritical: true,
  },
  {
    id: "DOT-004",
    criterion: "Calibración y Control de Calidad",
    text: "¿El equipo de rayos X tiene calibración y control de calidad vigente realizado por entidad avalada?",
    reference: "Res. 3100/2019 - Dotación",
    findingText: "Control de calidad (pruebas de fuga, kVp, tiempo, etc.) vencido o inexistente.",
    recommendation: "Contratar servicio técnico certificado para realizar las pruebas de control de calidad (anual o bienal).",
    isCritical: true,
  },
  {
    id: "DOT-005",
    criterion: "Mantenimiento preventivo",
    text: "¿Existe un programa documentado de mantenimiento preventivo para el equipo radiográfico?",
    reference: "Res. 3100/2019 - Dotación",
    findingText: "Programa de mantenimiento no estructurado o no documentado.",
    recommendation: "Elaborar manual y programa detallado estableciendo la periodicidad de su mantenimiento.",
  },
  {
    id: "DOT-006",
    criterion: "Cronograma de mantenimiento",
    text: "¿Se cuenta con cronograma de mantenimiento preventivo y correctivo con evidencia de cumplimiento?",
    reference: "Res. 3100/2019 - Dotación",
    findingText: "No hay reportes ni planillas que soporten el cumplimiento del cronograma.",
    recommendation: "Archivar las constancias emitidas por el ingeniero de soporte según el programa estipulado.",
  },
  {
    id: "DOT-007",
    criterion: "Hoja de vida del equipo",
    text: "¿El equipo de rayos X cuenta con hoja de vida actualizada con su serial, modelo e historial?",
    reference: "Res. 3100/2019 - Dotación",
    findingText: "Hoja de vida inexistente o desactualizada.",
    recommendation: "Crear formato u hoja de Excel de hoja de vida adjuntando todos los manuales y registros de mantenimientos.",
  },
  {
    id: "DOT-008",
    criterion: "Delantal plomado (paciente)",
    text: "¿Se dispone de delantal plomado para protección del paciente?",
    reference: "Protección radiológica",
    findingText: "Falta delantal plomado para paciente.",
    recommendation: "Adquirir chaleco con equivalencia mínima de plomo de 0.25mm o 0.5mm Eq Pb acorde a normativa.",
  },
  {
    id: "DOT-009",
    criterion: "Collar tiroideo (paciente)",
    text: "¿Se dispone de collar tiroideo plomado para protección del paciente?",
    reference: "Protección radiológica",
    findingText: "Falta protector tiroideo para paciente.",
    recommendation: "Adquirir collarín con banda de ajuste, equivalente de Pb según norma.",
  },
  {
    id: "DOT-010",
    criterion: "Elementos de protección (operador)",
    text: "¿El operador cuenta con elementos de protección radiológica personal (delantal/biombo)?",
    reference: "Res. 181434/2002",
    findingText: "El personal de salud no tiene protección blindada dispuesta.",
    recommendation: "Asegurar un delantal exclusivo para el trabajador o construir barrera protectora estructural de disparo.",
  },
  {
    id: "DOT-011",
    criterion: "Dosimetría personal",
    text: "¿Se cuenta con servicio de dosimetría personal activo para el personal ocupacionalmente expuesto (POE)?",
    reference: "Res. 181434/2002",
    findingText: "Ausencia de monitoreo dosimétrico personal.",
    recommendation: "Contratar mensualmente el servicio de recambio e informe de dosímetros de solapa.",
    isCritical: true,
  },
  {
    id: "DOT-012",
    criterion: "Receptores de imagen",
    text: "¿Se cuenta con sensor digital (RVG) o equipos para revelado con sus debidos posicionadores XCP?",
    reference: "Dotación mínima",
    findingText: "No hay receptores de imagen adecuados para realizar capturas funcionales.",
    recommendation: "Adquirir sensor intraoral con software y equipo de cómputo, o usar paquete de películas con cuarto oscuro/caja reveladora.",
  },
  {
    id: "DOT-013",
    criterion: "Sistema de visualización",
    text: "¿Se cuenta con sistema de visualización de imágenes (negatoscopio o monitor calibrado)?",
    reference: "Res. 3100/2019 - Dotación",
    findingText: "Falta de visualizador adecuado para emitir diagnóstico (monitor médico o negatoscopio).",
    recommendation: "Disponer monitor de resolución radiológica o negatoscopio bien iluminado para películas analógicas.",
  },
  {
    id: "DOT-014",
    criterion: "Cálculo de blindaje",
    text: "¿Se cuenta con el documento de cálculo de blindaje realizado por un físico médico o experto certificado?",
    reference: "Protección radiológica",
    findingText: "No hay soporte técnico-físico matemático sobre la atenuación de radiación del área.",
    recommendation: "Elaborar el cálculo de cargas de trabajo, factores de uso y ocupación mediante físico certificado y presentar memorias.",
    isCritical: true,
  }
];
